### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tpham93** [scikit-activeml/openml-scikit-activeml#1]
- [x] Creation of AL tasks
- [x] Local experiments
- [x] Predictions ARFF file 
- [x] Serialization
- [x] Version information of skactiveml
- [ ] Finalization of AL task
- [ ] Handling of extensions (explicit passing of the extension to use)
- [x] Testing of batch_size
- [x] Testing of annotation_cost
- [x] Minimal demo
- [x] Upload of flows (collision between sklearn and skactiveml extension)
- [ ] Upload of runs
    - [x] Upload of predictions file
    - [ ] Upload of utility file
        - header: repeat, fold, cycle, batch_idx, train_idx, utility, was_queried
- [ ] Evaluation based on annotation costs
- [ ] Frontend Task, Flow, Run
- [ ] Frontend evaluation visualization
